.SUFFIXES: .ASM .REL

.ASM.REL:
	M80 '=$< /I'
	
ALL: CCP.REL BDOS.REL B1MAIN.REL B2DISK.REL FDCNTR.REL B1CONIO.REL B1DISPB.REL B1LSTAUX.REL B0FLPDSK.REL B0RAMDSK.REL
	L80 CCP,BDOS,B1MAIN,B2DISK,FDCNTR,B1CONIO,B1DISPB,B1LSTAUX,B0FLPDSK,B0RAMDSK/X/E
